# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 053764551e3fff6739c46b4f7d1d569cacc132c910f753ea77eee8359ea8e01c92022f397d9139ce8b7c52a954b03e330c78091ccbca0ff139962e94d3dc5948

test:
  secret_key_base: 7fa54045694ac6e696727de13f8230c90ed426008d7b2e3c9bc792e0deca9166ea383bf06b032b0a2c69634e17e2c1a7c72cc3c73211d3d285c1b1791a8b4999

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
